name: app_uikit
description: App UI Kit
version: 0.0.1

environment:
  sdk: ">=3.1.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  # System
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  # flutter_native_splash: ^2.3.1
  auto_route: ^7.4.0
  equatable: ^2.0.5
  gaimon: ^1.2.0
  logger: ^2.0.2+1
  local_auth: ^2.1.7
  device_info_plus: ^9.0.3
  url_launcher: ^6.1.14

  # Code Generation
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

  # State Managment
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # Storage
  sqflite: ^2.3.0
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.2.0

  # Network
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1

  # UI
  google_fonts: ^6.1.0
  eva_icons_flutter: ^3.1.0
  modal_bottom_sheet: ^2.1.2
  pin_code_fields: ^8.0.1
  cached_network_image: ^3.3.0
  skeletons: ^0.0.3
  flutter_easy_dialogs: ^3.1.2
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
